name: Release NuGet Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install MinVer CLI
        run: dotnet tool install --global minver-cli --version 6.0.0

      - name: Get Version
        id: minver
        run: |
          VERSION=$(minver -t v --default-pre-release-phase "" --minimum-major-minor 1.0)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Restore
        run: dotnet restore dapperEfLike.sln

      - name: Build
        run: dotnet build dapperEfLike.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test dapperEfLike.sln --configuration Release --no-build --no-restore

      - name: Pack
        run: dotnet pack DapperOrmCore/DapperOrmCore.csproj --configuration Release --no-build --no-restore -o ./nupkgs -p:Version=${{ steps.minver.outputs.VERSION }}

      - name: Create Git Tag if it doesn't exist
        run: |
          if ! git rev-parse "v${{ steps.minver.outputs.VERSION }}" >/dev/null 2>&1; then
            git tag v${{ steps.minver.outputs.VERSION }}
            git push origin v${{ steps.minver.outputs.VERSION }}
          else
            echo "Tag v${{ steps.minver.outputs.VERSION }} already exists. Skipping tag creation."
          fi

      - name: Push
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
